name: New IOOS Repository Request
description: Request a new repository under the IOOS Organization
labels: repo
body:
  - type: markdown
    attributes:
      value: |
        Complete the form fields below describing your proposed repository.  Enter an appropriate issue title (e.g. 'Create cool-ioos-project repo').

  - type: input
    id: repo-name
    attributes:
      label: Repository name
      placeholder: <enter repo name>
    validations:
      required: true

  - type: textarea
    id: repo-purpose
    attributes:
      label: Repository purpose
      description: |
        Please describe in a few sentences why this repository is approrpriate for the IOOS GitHub Organization.  A few questions for consideration: does it relate to an IOOS project, is it being developed by IOOS personnel or partners, does it add to or compliment existing IOOS packages or modules?  If the answer is yes to any of these questions, then it likely belongs here - just tell us why.
    validations:
      required: true

  - type: textarea
    id: repo-description
    attributes:
      label: Repository description
      description: |
        Provide a public description of the repository (this will be entered into the corresponding repository description field if accepted).
    validations:
      required: true
     
  - type: dropdown
    id: repo-type
    attributes:
      label: Repository type
      description: |
        IOOS allows only Public GitHub repostories.  Please file a separate issue in this repository if you feel we need to reconsider this policy.
      options:
        - Public
    validations:
      required: true      

  - type: dropdown
    id: repo-license
    attributes:
      label: Repository license
      description: |
        Which license should be applied? IOOS prefers BSD-3 for software and CC0 v1.0 for documentation.
      options:
        - BSD 3-Clause
        - Creative Commons Zero v1.0 Universal
        - Apache License 2.0
        - GNU General Public License v2.0
        - MIT License
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ## Optional information
  
  - type: checkboxes
    id: repo-options
    attributes:
      label: Repository options
      description: |
        Select options for creating the new repository
      options:
        - label: "Add a README.md file"
        - label: "Add a .gitignore file"
  
  - type: input
    id: repo-gitignore-type
    attributes:
      label: Specify a .gitignore file type
      description: If the repository should have a .gitignore file, choose from the .gitignore language/file types listed [here](https://github.com/github/gitignore).  
      placeholder: <enter .gitignore file type (e.g. Python.gitignore)>

  - type: input
    id: gh-user-name
    attributes:
      label: Specify GitHub usernames or IOOS GitHub Team for repository access
      description: Specify who should have access to this repository and what [role](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#repository-roles-for-organizations)(excluding Admin) they should have. List the GitHub usernames or the appropriate [IOOS GitHub Team](https://github.com/orgs/ioos/teams) followed by the role.
      placeholder: ioos/biodata **Maintain**

  - type: markdown
    attributes:
      value: |
        We reserve the right to adjust the permissions/access list in situations where an existing team or group can be used for simplicity sake.
